name: blind_assist_app
description: A blind assistance Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  http: ^1.2.0
  location: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true