name: blind_assist_app
description: A blind assistance Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  http: ^1.2.0
  location: ^5.0.0
  # firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.1.5
  google_generative_ai: ^0.4.7
  grpc: ^3.0.0 # Check for latest version
  protobuf: ^3.0.0 # Check for latest version
  
  geolocator: ^11.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/GeminEye_Logo.png"

flutter:
  assets:
    - assets/image/google_logo.png
    - assets/image/GeminEye_Logo.png
  uses-material-design: true