# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blind_assist.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'blind_assist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62lind_assist.proto\x12\ngeminilive\"\xfe\x01\n\rClientRequest\x12:\n\x0einitial_config\x18\x01 \x01(\x0b\x32 .geminilive.InitialConfigRequestH\x00\x12)\n\ttext_part\x18\x02 \x01(\x0b\x32\x14.geminilive.TextPartH\x00\x12+\n\nimage_part\x18\x03 \x01(\x0b\x32\x15.geminilive.ImagePartH\x00\x12\x32\n\x11\x63lient_audio_part\x18\x04 \x01(\x0b\x32\x15.geminilive.AudioPartH\x00\x12\x15\n\x0b\x65nd_of_turn\x18\x05 \x01(\x08H\x00\x42\x0e\n\x0crequest_data\"G\n\x14InitialConfigRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x1b\n\x13response_modalities\x18\x02 \x03(\t\"\x18\n\x08TextPart\x12\x0c\n\x04text\x18\x01 \x01(\t\"2\n\tImagePart\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\tmime_type\x18\x02 \x01(\t\"G\n\tAudioPart\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\"\xc6\x01\n\x0eServerResponse\x12)\n\ttext_part\x18\x01 \x01(\x0b\x32\x14.geminilive.TextPartH\x00\x12\x32\n\x11gemini_audio_part\x18\x02 \x01(\x0b\x32\x15.geminilive.AudioPartH\x00\x12+\n\nerror_part\x18\x03 \x01(\x0b\x32\x15.geminilive.ErrorPartH\x00\x12\x17\n\rturn_complete\x18\x04 \x01(\x08H\x00\x42\x0f\n\rresponse_data\"*\n\tErrorPart\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32U\n\nGeminiLive\x12G\n\nChatStream\x12\x19.geminilive.ClientRequest\x1a\x1a.geminilive.ServerResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blind_assist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTREQUEST']._serialized_start=35
  _globals['_CLIENTREQUEST']._serialized_end=289
  _globals['_INITIALCONFIGREQUEST']._serialized_start=291
  _globals['_INITIALCONFIGREQUEST']._serialized_end=362
  _globals['_TEXTPART']._serialized_start=364
  _globals['_TEXTPART']._serialized_end=388
  _globals['_IMAGEPART']._serialized_start=390
  _globals['_IMAGEPART']._serialized_end=440
  _globals['_AUDIOPART']._serialized_start=442
  _globals['_AUDIOPART']._serialized_end=513
  _globals['_SERVERRESPONSE']._serialized_start=516
  _globals['_SERVERRESPONSE']._serialized_end=714
  _globals['_ERRORPART']._serialized_start=716
  _globals['_ERRORPART']._serialized_end=758
  _globals['_GEMINILIVE']._serialized_start=760
  _globals['_GEMINILIVE']._serialized_end=845
# @@protoc_insertion_point(module_scope)
