# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import blind_assist_pb2 as blind__assist__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in blind_assist_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeminiLiveStub(object):
    """Service definition for Gemini Live API interaction
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.stream_stream(
                '/geminilive.GeminiLive/ChatStream',
                request_serializer=blind__assist__pb2.ClientRequest.SerializeToString,
                response_deserializer=blind__assist__pb2.ServerResponse.FromString,
                _registered_method=True)


class GeminiLiveServicer(object):
    """Service definition for Gemini Live API interaction
    """

    def ChatStream(self, request_iterator, context):
        """Bidirectional stream for continuous interaction with Gemini.
        The client streams text, image frames, and audio.
        The server streams back Gemini's responses (text, audio).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeminiLiveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=blind__assist__pb2.ClientRequest.FromString,
                    response_serializer=blind__assist__pb2.ServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geminilive.GeminiLive', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geminilive.GeminiLive', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeminiLive(object):
    """Service definition for Gemini Live API interaction
    """

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/geminilive.GeminiLive/ChatStream',
            blind__assist__pb2.ClientRequest.SerializeToString,
            blind__assist__pb2.ServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
