# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gemini_chat_pb2 as gemini__chat__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gemini_chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeminiChatStub(object):
    """定義 Gemini Chat 服務
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/geminiChat.GeminiChat/CreateSession',
                request_serializer=gemini__chat__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=gemini__chat__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.stream_stream(
                '/geminiChat.GeminiChat/ChatStream',
                request_serializer=gemini__chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=gemini__chat__pb2.ChatResponse.FromString,
                _registered_method=True)


class GeminiChatServicer(object):
    """定義 Gemini Chat 服務
    """

    def CreateSession(self, request, context):
        """建立新會話，並可選擇性提供 API 金鑰
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request_iterator, context):
        """雙向串流：客戶端可以流式送多筆 audio/image 訊息，後端流式回應
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeminiChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=gemini__chat__pb2.CreateSessionRequest.FromString,
                    response_serializer=gemini__chat__pb2.CreateSessionResponse.SerializeToString,
            ),
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=gemini__chat__pb2.ChatRequest.FromString,
                    response_serializer=gemini__chat__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geminiChat.GeminiChat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geminiChat.GeminiChat', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeminiChat(object):
    """定義 Gemini Chat 服務
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geminiChat.GeminiChat/CreateSession',
            gemini__chat__pb2.CreateSessionRequest.SerializeToString,
            gemini__chat__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/geminiChat.GeminiChat/ChatStream',
            gemini__chat__pb2.ChatRequest.SerializeToString,
            gemini__chat__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
